substitutions:
  _REGION: "us-central1"
  _RUNTIME: "python312"
  _REQ_TOPIC: "edgarai-request"
  _RES_TOPIC: "edgarai-response"
  _STORAGE_PREFIX: "gs://edgar_666/newfuncs"
  _LOG_LEVEL: "DEBUG"
  _SERVICE_ACCOUNT: "edgar-dev@edgar-ai.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "functions"
      - "deploy"
      - "edgar_req_processor"
      - "--gen2"
      - "--region=${_REGION}"
      - "--runtime=${_RUNTIME}"
      - "--memory=2G"
      - "--timeout=540s"
      - "--max-instances=5"
      - "--service-account"
      - "${_SERVICE_ACCOUNT}"
      - "--trigger-topic=${_REQ_TOPIC}"
      - "--entry-point=req_processor"
      - "--source"
      - "."
      - "--set-env-vars"
      - "STORAGE_PREFIX=${_STORAGE_PREFIX},RESPONSE_TOPIC=${_RES_TOPIC},LOG_LEVEL=${_LOG_LEVEL}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "functions"
      - "deploy"
      - "edgar_resp_processor"
      - "--gen2"
      - "--region=${_REGION}"
      - "--runtime=${_RUNTIME}"
      - "--memory=512M"
      - "--timeout=60s"
      - "--max-instances=10"
      - "--service-account"
      - "${_SERVICE_ACCOUNT}"
      - "--trigger-topic=${_RES_TOPIC}"
      - "--entry-point=resp_processor"
      - "--source"
      - "."
      - "--set-env-vars"
      - "STORAGE_PREFIX=${_STORAGE_PREFIX},REQUEST_TOPIC=${_REQ_TOPIC},LOG_LEVEL=${_LOG_LEVEL}"
