# this workflow will be triggered when
#
#  1. a pull request is raised
#  2. a push to 'develop' branch takes place
#  3. a release tag is created on the repo
#
#  whenever the event is trigger, build and test will be performed
#  a container image will be created and pushed to ghcr.io only when the event trigger is push to develop or tag.
#
#  for push to develop branch, develop-YYYYMMDD-HHMISS-SHA7. the tagging should be sortable by chronological order so that
#  it can be picked up by CD tools, e.g. FluxCD, for updating the deployment automatically
#
#  for new tag, the image tag will be same as the repository tag. e.g. v0.1.0
#
#  CAVEATS:
#
#  does not support copmlete gitflow that uses long running release branches.
#
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.12

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install Python using uv ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync

      - name: Linting
        run: |
          uv run ruff check .

      - name: Unit tests
        id: unit_tests
        run: |
          uv run pytest -v -s --cov --cov-report=html

          if [[ -f "htmlcov/index.html" ]]; then
            echo "coverage_report=no" >> $GITHUB_OUTPUT
          fi
        env:
          # just some value in order to make unit test pass
          CLI_EDGAR_PROCESSOR_URL: "http://example.com"

      - name: Upload test coverage report to GitHub pages
        if: steps.unit_tests.outputs.coverage_report == 'yes'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: htmlcov
        continue-on-error: true
